# 图片访问
domain: "http://127.0.0.1:8080"
# goole15
goole: ""
# 开启特殊标记增强
flags: true
# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:8080"
  model: "bing"
  token: "17QgvFufwjeHS0Uk0Fflg8_7vMYG-gvyEqjB4Fx68ExrpLtAsnm5rbgxh_HjdTb8CjRDFvsuNW3DqWOV_F0tFfJHXOymhu4Pc9DJZ_s3MyiwepzBRsxD0Up9jtQWUz6QFVXRrifEkpwEakO8xinqs9Su_bH4KYdJXesehEjtax452S3juTZhDW0xNhMTURMhhKyUXwizk2KOr32KCSTaPCQ"
# 图片放大，domain需要公网可访问的地址
# key请到https://bigjpg.com获取，每月30次免费
# 目前注册没有限制，可配置多个key轮询
#magnify:
#  - "xxx"