# 图片访问
domain: "http://127.0.0.1:8080"
# goole15
goole: ""
# 开启特殊标记增强
flags: true
# 内调llm，用于绘图时文本转tags
llm:
  baseUrl: "http://127.0.0.1:8080"
  model: "bing"
  token: "xxx"
# 图片放大
magnify:
  - "910d9be5b5ca4621b7a3eee954c26b1e"